# .github/workflows/app.yaml
name: Run PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"

      - name: build and start containers
        run: docker-compose up -d

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run tests with pytest
        run: pytest
